# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "juan-pablo-villegas"
license = "MIT"
licenselink = "https://github.com/aficiomaquinas/juan-pablo-villegas/blob/master/LICENSE"
description = "Artist portfolio"
homepage = "http://www.jpvd.xyz/"
min_version = 0.14

[author]
  name = "Victor Gonzalez"
  homepage = "http://victtor.com"