title = "Juan Pablo Villegas"
theme = "juan-pablo-villegas"
baseurl = "http://jpvd.xyz/"
languageCode = "en-us"
googleAnalytics = ""
relativeurls = true

[permalinks]
	artwork = "/:year/:title/"
	page = "/:title/"