title = "Juan-Pablo Villegas"
theme = "juan-pablo-villegas"
baseurl = "http://www.jpvd.xyz/"
languageCode = "en-us"
googleAnalytics = "UA-81206703-1"
relativeurls = true

[permalinks]
	artwork = "/:year/:title/"
	page = "/:title/"