baseurl = "http://www.jpvd.xyz/"
googleAnalytics = "UA-81206703-1"
languageCode = "en-us"
relativeurls = true
theme = "juan-pablo-villegas"
title = "Juan-Pablo Villegas"
[permalinks]
artwork = "/:year/:title/"
page = "/:title/"
